name: build

on:
  push:
    branches:
      - main

jobs:
  R-CMD:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: 'devel'}
        - { os: macos-latest, r: 'devel'}
        - { os: ubuntu-latest, r: 'devel', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true      
      GITHUB_PAT: ${{ secrets.GH_PAT_RFASST}}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: '3.6'
      - uses: r-lib/actions/setup-pandoc@v2-branch
      - uses: r-lib/actions/setup-tinytex@v2-branch
      
      - name: Cache R packages 
        uses: actions/cache@v1 
        with: 
          path: ${{ env.R_LIBS_USER }} 
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }} 
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1- 
      
      - name: Ubuntu config
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev libmagick++-dev libavfilter-dev
      
      - name: MacOS Config
        if: startsWith(matrix.config.os, 'macOS')
        run: |
            brew install pkg-config
            brew install gdal
            brew install geos
            brew install imagemagick@6
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes","rcmdcheck"), repos = "https://cloud.r-project.org")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
           
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}